// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[PrimaryKey("Batch", "ObjectId", "OrderNumber")]
[Table("BATCH_OBJECTS")]
[Index("ObjectId", Name = "idx_BATCH_OBJECTS_OBJECTID")]
public partial class BatchObjects
{
    [Key]
    [Column("BATCH")]
    [StringLength(20)]
    [Unicode(false)]
    public string Batch { get; set; }

    [Key]
    [Column("OBJECT_ID")]
    public int ObjectId { get; set; }

    [Key]
    [Column("ORDER_NUMBER")]
    public int OrderNumber { get; set; }

    [Column("SAMPLE_TYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string SampleType { get; set; }

    [Column("REFERENCE_SAMPLE")]
    public int? ReferenceSample { get; set; }

    [Column("PARAMETER_1")]
    [StringLength(20)]
    [Unicode(false)]
    public string Parameter1 { get; set; }

    [Column("PARAMETER_2")]
    [StringLength(20)]
    [Unicode(false)]
    public string Parameter2 { get; set; }

    [Column("SAMPLE_NUMBER")]
    public int? SampleNumber { get; set; }
}