// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[PrimaryKey("BatchProtocol", "OrderNumber")]
[Table("BATCH_STANDARD")]
public partial class BatchStandard
{
    [Key]
    [Column("BATCH_PROTOCOL")]
    [StringLength(20)]
    [Unicode(false)]
    public string BatchProtocol { get; set; }

    [Key]
    [Column("ORDER_NUMBER")]
    public int OrderNumber { get; set; }

    [Column("STANDARD")]
    [StringLength(50)]
    [Unicode(false)]
    public string Standard { get; set; }

    [Column("POSITION")]
    public int? Position { get; set; }

    [Column("STARTING_POS")]
    public int? StartingPos { get; set; }

    [Column("REPEAT_INTERVAL")]
    public int? RepeatInterval { get; set; }

    [Column("REPEATING_STD")]
    [StringLength(1)]
    [Unicode(false)]
    public string RepeatingStd { get; set; }

    [Column("STANDARD_REAGENT")]
    [StringLength(20)]
    [Unicode(false)]
    public string StandardReagent { get; set; }

    [Column("STANDARD_REAG_TMPL")]
    [StringLength(20)]
    [Unicode(false)]
    public string StandardReagTmpl { get; set; }

    [Column("CONCENTRATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string Concentration { get; set; }
}