// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[PrimaryKey("Template", "FieldName", "Version")]
[Table("BATCH_HDR_TMP_FLDS")]
public partial class BatchHdrTmpFlds
{
    [Key]
    [Column("TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Template { get; set; }

    [Key]
    [Column("FIELD_NAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string FieldName { get; set; }

    [Column("ENTRY_MODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string EntryMode { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("DEFAULT_VALUE")]
    [StringLength(254)]
    [Unicode(false)]
    public string DefaultValue { get; set; }

    [Column("FIELD_LABEL")]
    [StringLength(30)]
    [Unicode(false)]
    public string FieldLabel { get; set; }

    [Column("FORMULA", TypeName = "text")]
    public string Formula { get; set; }

    [Column("ALLOW_USER_ENTRY")]
    [StringLength(1)]
    [Unicode(false)]
    public string AllowUserEntry { get; set; }

    [Key]
    [Column("VERSION")]
    public int Version { get; set; }

    [Column("DATA_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string DataType { get; set; }

    [Column("DEPENDS_ON")]
    [StringLength(254)]
    [Unicode(false)]
    public string DependsOn { get; set; }
}