// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[PrimaryKey("Name", "Version")]
[Table("BATCH_HDR_TEMPLATE")]
[Index("AnalysisLinkKey", Name = "BATCH_HDR_TEM13802")]
[Index("ChangeLinkKey", Name = "BATCH_HDR_TEMP5792")]
public partial class BatchHdrTemplate
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Key]
    [Column("VERSION")]
    public int Version { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("NAME_PREFIX")]
    [StringLength(20)]
    [Unicode(false)]
    public string NamePrefix { get; set; }

    [Column("ID_CONFIG")]
    [StringLength(20)]
    [Unicode(false)]
    public string IdConfig { get; set; }

    [Column("GLOBAL_FLAG")]
    [StringLength(1)]
    [Unicode(false)]
    public string GlobalFlag { get; set; }

    [Column("BATCH_PROTOCOL")]
    [StringLength(20)]
    [Unicode(false)]
    public string BatchProtocol { get; set; }

    [Column("ASSIGN_TO_OBJECTS")]
    [StringLength(1)]
    [Unicode(false)]
    public string AssignToObjects { get; set; }

    [Column("ANALYSIS_LINK_FIELD")]
    [StringLength(20)]
    [Unicode(false)]
    public string AnalysisLinkField { get; set; }

    [Column("ANALYSIS_LINK_KEY")]
    [StringLength(20)]
    [Unicode(false)]
    public string AnalysisLinkKey { get; set; }

    [Column("CHANGE_LINK_KEY")]
    [StringLength(1)]
    [Unicode(false)]
    public string ChangeLinkKey { get; set; }

    [Column("FOLDER_TAG")]
    [StringLength(50)]
    [Unicode(false)]
    public string FolderTag { get; set; }

    [Column("REQUIRED_NUM")]
    public int? RequiredNum { get; set; }

    [Column("MAXIMUM_NUM")]
    public int? MaximumNum { get; set; }

    [Column("REFRESH_INTERVAL")]
    public int? RefreshInterval { get; set; }

    [Column("ADD_IF_BATCHED")]
    [StringLength(1)]
    [Unicode(false)]
    public string AddIfBatched { get; set; }

    [Column("BATCH_REPORT")]
    [StringLength(50)]
    [Unicode(false)]
    public string BatchReport { get; set; }

    [Column("OBJECT_CLASS")]
    [StringLength(20)]
    [Unicode(false)]
    public string ObjectClass { get; set; }

    [Column("SCAN_FIELD")]
    [StringLength(50)]
    [Unicode(false)]
    public string ScanField { get; set; }

    [Column("BATCH_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string BatchType { get; set; }

    [Column("EDIT_TEST_TEMP")]
    [StringLength(20)]
    [Unicode(false)]
    public string EditTestTemp { get; set; }

    [Column("EDIT_SAMPLE_TEMP")]
    [StringLength(20)]
    [Unicode(false)]
    public string EditSampleTemp { get; set; }

    [Column("CHART_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChartGroup { get; set; }

    [Column("C_BATCH_PROTOCOL")]
    [StringLength(20)]
    [Unicode(false)]
    public string CBatchProtocol { get; set; }

    [Column("FILE_EXPORT_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string FileExportType { get; set; }
}