// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_ACCREDITATION")]
public partial class CAccreditation
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Required]
    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Required]
    [Column("COMPONENT")]
    [StringLength(60)]
    [Unicode(false)]
    public string Component { get; set; }

    [Column("VERSION")]
    public int Version { get; set; }

    [Column("ORDER_NUMBER")]
    public int OrderNumber { get; set; }

    [Required]
    [Column("MATRIX")]
    [StringLength(2)]
    [Unicode(false)]
    public string Matrix { get; set; }

    [Column("ACCREDITATION")]
    [StringLength(1)]
    [Unicode(false)]
    public string Accreditation { get; set; }

    [Column("Q_CODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string QCode { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }
}