// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("Analysis", "Component", "Name", "Version")]
[Table("CALC_VARIABLES")]
[Index("Name", Name = "CALC_VARIABLES2191")]
[Index("Analysis", Name = "CALC_VARIABLES6558")]
[Index("Component", Name = "CALC_VARIABLES9973")]
public partial class CalcVariables
{
    [Key]
    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Key]
    [Column("COMPONENT")]
    [StringLength(60)]
    [Unicode(false)]
    public string Component { get; set; }

    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Key]
    [Column("VERSION")]
    public int Version { get; set; }

    [Column("REFERENCE_TYPE")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReferenceType { get; set; }

    [Column("REFERENCE_NAME")]
    [StringLength(40)]
    [Unicode(false)]
    public string ReferenceName { get; set; }

    [Column("ATTRIBUTE_1")]
    [StringLength(100)]
    [Unicode(false)]
    public string Attribute1 { get; set; }

    [Column("RETURN_VALUE")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReturnValue { get; set; }

    [Column("SCOPE")]
    [StringLength(2)]
    [Unicode(false)]
    public string Scope { get; set; }

    [Column("FUNCTION")]
    [StringLength(15)]
    [Unicode(false)]
    public string Function { get; set; }

    [Column("RESULT_FIELD")]
    [StringLength(50)]
    [Unicode(false)]
    public string ResultField { get; set; }

    [Column("SPECIFIC_ANALYSIS")]
    [StringLength(1)]
    [Unicode(false)]
    public string SpecificAnalysis { get; set; }

    [Column("ATTRIBUTE_2")]
    [StringLength(40)]
    [Unicode(false)]
    public string Attribute2 { get; set; }

    [Column("CALC_TRIGGER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CalcTrigger { get; set; }
}