// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("Name", "Version")]
[Table("CATALOGUE")]
[Index("Name", Name = "CATALOGUE_NAM15097")]
public partial class Catalogue
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Key]
    [Column("VERSION")]
    public int Version { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(25)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("EFFECTIVE_DATE", TypeName = "datetime")]
    public DateTime? EffectiveDate { get; set; }

    [Column("APPROVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Approved { get; set; }

    [Column("APPROVAL_GROUP")]
    [StringLength(10)]
    [Unicode(false)]
    public string ApprovalGroup { get; set; }

    [Column("READY_FOR_APPROVAL")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReadyForApproval { get; set; }

    [Column("APPROVAL_ID")]
    public int? ApprovalId { get; set; }

    [Column("ACTIVE_FLAG")]
    [StringLength(1)]
    [Unicode(false)]
    public string ActiveFlag { get; set; }

    [Column("CATALOGUE_CURRENCY")]
    [StringLength(20)]
    [Unicode(false)]
    public string CatalogueCurrency { get; set; }

    [Column("SEARCH_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SearchTemplate { get; set; }

    [Column("DEFAULT_TAX_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string DefaultTaxGroup { get; set; }

    [Column("QUANT_PRICE_IS_DISC")]
    [StringLength(1)]
    [Unicode(false)]
    public string QuantPriceIsDisc { get; set; }

    [Column("REPORT_FORMAT")]
    [StringLength(20)]
    [Unicode(false)]
    public string ReportFormat { get; set; }

    [Column("COST_ITEM_DISCOUNT")]
    public int? CostItemDiscount { get; set; }
}