// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("CATALOGUE_ITEM")]
[Index("Catalogue", "Version", Name = "idxCATALOGUE_ITEM_CATVER")]
public partial class CatalogueItem
{
    [Required]
    [Column("CATALOGUE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Catalogue { get; set; }

    [Column("VERSION")]
    public int Version { get; set; }

    [Column("COST_ITEM_NO")]
    public int CostItemNo { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("ITEM_CODE")]
    [StringLength(30)]
    [Unicode(false)]
    public string ItemCode { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("LIST_PRICE")]
    [StringLength(10)]
    [Unicode(false)]
    public string ListPrice { get; set; }

    [Column("QUANTITY_1")]
    public int? Quantity1 { get; set; }

    [Column("QUANTITY_1_PRICE")]
    public float? Quantity1Price { get; set; }

    [Column("QUANTITY_2")]
    public int? Quantity2 { get; set; }

    [Column("QUANTITY_2_PRICE")]
    public float? Quantity2Price { get; set; }

    [Column("QUANTITY_3")]
    public int? Quantity3 { get; set; }

    [Column("QUANTITY_3_PRICE")]
    public float? Quantity3Price { get; set; }

    [Column("CUMULATIVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string Cumulative { get; set; }

    [Key]
    [Column("CATALOGUE_ITEM_NO")]
    public int CatalogueItemNo { get; set; }

    [Column("TAX_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string TaxGroup { get; set; }

    [Column("DISCOUNTABLE")]
    [StringLength(1)]
    [Unicode(false)]
    public string Discountable { get; set; }
}