// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_CHARACTER")]
[Index("Code", Name = "idxCharacterCode")]
public partial class CCharacter
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("CUSTOMER")]
    [StringLength(20)]
    public string Customer { get; set; }

    [Required]
    [Column("OBJECT_CLASS")]
    [StringLength(50)]
    public string ObjectClass { get; set; }

    [Column("ORDER_NUMBER")]
    public short? OrderNumber { get; set; }

    [Required]
    [Column("CODE")]
    [StringLength(4)]
    public string Code { get; set; }

    [Required]
    [Column("DESCRIPTION")]
    [StringLength(50)]
    public string Description { get; set; }

    [Column("PRINTEN")]
    public short? Printen { get; set; }

    [Column("TYPE")]
    [StringLength(15)]
    public string Type { get; set; }

    [Column("DEFINITION")]
    [StringLength(60)]
    public string Definition { get; set; }

    [Column("KM_REQ")]
    [StringLength(1)]
    public string KmReq { get; set; }

    [Column("ACTIVE")]
    [StringLength(1)]
    public string Active { get; set; }

    [Column("REFERENCE")]
    [StringLength(1)]
    public string Reference { get; set; }

    [Column("MIN")]
    [StringLength(60)]
    public string Min { get; set; }

    [Column("MAX")]
    [StringLength(60)]
    public string Max { get; set; }

    [Column("CTYPE")]
    [StringLength(8)]
    public string Ctype { get; set; }

    [Column("COLNAME")]
    [StringLength(18)]
    public string Colname { get; set; }

    [Column("OPM_NR")]
    public int? OpmNr { get; set; }

    [Column("CREATED_BY")]
    [StringLength(20)]
    public string CreatedBy { get; set; }

    [Column("CREATED_ON")]
    public DateTime? CreatedOn { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON")]
    public DateTime? ChangedOn { get; set; }
}