// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_DISCLAIMER_REG")]
public partial class CDisclaimerReg
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("OBJECT_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ObjectType { get; set; }

    [Column("OBJECT_ID")]
    public int? ObjectId { get; set; }

    [Column("DISCLAIMER")]
    public int? Disclaimer { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }
}