// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_DISCLAIMERS")]
public partial class CDisclaimers
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("NIVEAU")]
    [StringLength(20)]
    public string Niveau { get; set; }

    [Column("CATEGORY")]
    [StringLength(20)]
    public string Category { get; set; }

    [Column("CODE")]
    [StringLength(20)]
    public string Code { get; set; }

    [Column("DISCLAIMER")]
    public string Disclaimer { get; set; }

    [Column("DISCLAIMER_EN")]
    public string DisclaimerEn { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("DESCRIPTION_EN")]
    [StringLength(254)]
    public string DescriptionEn { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("REPORTABLE")]
    [StringLength(1)]
    [Unicode(false)]
    public string Reportable { get; set; }
}