// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_MATRIX_DETAILS")]
[Index("CMatrix", "SampleType", Name = "idx_CMATRIXDETAILS", IsUnique = true)]
public partial class CMatrixDetails
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Required]
    [Column("C_MATRIX")]
    [StringLength(4)]
    [Unicode(false)]
    public string CMatrix { get; set; }

    [Required]
    [Column("SAMPLE_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SampleType { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("DESCRIPTION_EN")]
    [StringLength(254)]
    [Unicode(false)]
    public string DescriptionEn { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }
}