// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("COLLECTION_RUN")]
public partial class CollectionRun
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("T_DURATION")]
    public int? TDuration { get; set; }

    [Column("T_HOLIDAY_SCHEDULE")]
    [StringLength(20)]
    [Unicode(false)]
    public string THolidaySchedule { get; set; }

    [Column("T_NOTES")]
    public int? TNotes { get; set; }

    [Column("T_ON_HOLIDAYS")]
    [StringLength(1)]
    [Unicode(false)]
    public string TOnHolidays { get; set; }

    [Column("C_SAMPLER_ID")]
    [StringLength(20)]
    [Unicode(false)]
    public string CSamplerId { get; set; }
}