// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("Analysis", "Name", "Version")]
[Table("COMPONENT")]
[Index("Analysis", Name = "COMPONENT_ANA13302")]
[Index("Name", Name = "COMPONENT_NAM11051")]
[Index("Units", Name = "COMPONENT_UNIT9125")]
public partial class Component
{
    [Key]
    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Key]
    [Column("NAME")]
    [StringLength(60)]
    [Unicode(false)]
    public string Name { get; set; }

    [Key]
    [Column("VERSION")]
    public int Version { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("RESULT_TYPE")]
    [StringLength(1)]
    [Unicode(false)]
    public string ResultType { get; set; }

    [Column("UNITS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Units { get; set; }

    [Column("MINIMUM")]
    [StringLength(20)]
    [Unicode(false)]
    public string Minimum { get; set; }

    [Column("MAXIMUM")]
    [StringLength(20)]
    [Unicode(false)]
    public string Maximum { get; set; }

    [Column("ALLOW_OUT")]
    [StringLength(1)]
    [Unicode(false)]
    public string AllowOut { get; set; }

    [Column("PLACES")]
    public int? Places { get; set; }

    [Column("NUM_REPLICATES")]
    public int? NumReplicates { get; set; }

    [Column("USES_INSTRUMENT")]
    [StringLength(1)]
    [Unicode(false)]
    public string UsesInstrument { get; set; }

    [Column("USES_CODES")]
    [StringLength(1)]
    [Unicode(false)]
    public string UsesCodes { get; set; }

    [Column("AUTO_CALC")]
    [StringLength(1)]
    [Unicode(false)]
    public string AutoCalc { get; set; }

    [Column("LIST_KEY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ListKey { get; set; }

    [Column("ALLOW_CANCEL")]
    [StringLength(1)]
    [Unicode(false)]
    public string AllowCancel { get; set; }

    [Column("CAS_NUMBER")]
    [StringLength(20)]
    [Unicode(false)]
    public string CasNumber { get; set; }

    [Column("ALIAS_NAME")]
    [StringLength(40)]
    [Unicode(false)]
    public string AliasName { get; set; }

    [Column("REPORTABLE")]
    [StringLength(1)]
    [Unicode(false)]
    public string Reportable { get; set; }

    [Column("OPTIONAL")]
    [StringLength(1)]
    [Unicode(false)]
    public string Optional { get; set; }

    [Column("ROUND")]
    [StringLength(20)]
    [Unicode(false)]
    public string Round { get; set; }

    [Column("CLAMP_LOW")]
    [StringLength(20)]
    [Unicode(false)]
    public string ClampLow { get; set; }

    [Column("CLAMP_HIGH")]
    [StringLength(20)]
    [Unicode(false)]
    public string ClampHigh { get; set; }

    [Column("STD_REAG_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string StdReagTemplate { get; set; }

    [Column("HAS_ATTRIBUTES")]
    [StringLength(1)]
    [Unicode(false)]
    public string HasAttributes { get; set; }

    [Column("FORMAT_CALCULATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string FormatCalculation { get; set; }

    [Column("DISPLAYED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Displayed { get; set; }

    [Column("VERSION_FILES")]
    [StringLength(1)]
    [Unicode(false)]
    public string VersionFiles { get; set; }

    [Column("BROWSE_SUBROUTINE")]
    [StringLength(50)]
    [Unicode(false)]
    public string BrowseSubroutine { get; set; }

    [Column("STEP")]
    [StringLength(20)]
    [Unicode(false)]
    public string Step { get; set; }

    [Column("NWA_NAME")]
    [StringLength(32)]
    [Unicode(false)]
    public string NwaName { get; set; }

    [Column("PLACES_2")]
    public int? Places2 { get; set; }

    [Column("REPORTED_RESULT")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReportedResult { get; set; }

    [Column("CONVERSION_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ConversionType { get; set; }

    [Column("FROM_CATEGORY")]
    [StringLength(20)]
    [Unicode(false)]
    public string FromCategory { get; set; }

    [Column("TO_CATEGORY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ToCategory { get; set; }

    [Column("FROM_UNITS")]
    [StringLength(20)]
    [Unicode(false)]
    public string FromUnits { get; set; }

    [Column("TO_UNITS")]
    [StringLength(20)]
    [Unicode(false)]
    public string ToUnits { get; set; }

    [Column("CONVERSION_FACTOR")]
    public float? ConversionFactor { get; set; }

    [Column("T_SHORT_NAME")]
    [StringLength(17)]
    [Unicode(false)]
    public string TShortName { get; set; }

    [Column("T_MDL")]
    [StringLength(10)]
    [Unicode(false)]
    public string TMdl { get; set; }

    [Column("T_MRL")]
    [StringLength(10)]
    [Unicode(false)]
    public string TMrl { get; set; }

    [Column("REPORTED_NAME")]
    [StringLength(60)]
    [Unicode(false)]
    public string ReportedName { get; set; }

    [Column("C_SIKB_CODE")]
    public int? CSikbCode { get; set; }

    [Column("C_REWAB_CODE")]
    public int? CRewabCode { get; set; }

    [Column("C_CADRI_CODE")]
    [StringLength(12)]
    [Unicode(false)]
    public string CCadriCode { get; set; }
}