// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("CONTAINER_TYPE")]
public partial class ContainerType
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("CONTAINER_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string ContainerGroup { get; set; }

    [Column("VOLUME")]
    public int? Volume { get; set; }

    [Column("VOLUME_UNITS")]
    [StringLength(20)]
    [Unicode(false)]
    public string VolumeUnits { get; set; }

    [Column("UNIQUE_SAMPLES")]
    [StringLength(1)]
    [Unicode(false)]
    public string UniqueSamples { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("T_CLASS")]
    [StringLength(20)]
    [Unicode(false)]
    public string TClass { get; set; }

    [Column("T_DISPATCH_NAME")]
    [StringLength(100)]
    [Unicode(false)]
    public string TDispatchName { get; set; }

    [Column("T_DISPATCH_VESSEL")]
    [StringLength(1)]
    [Unicode(false)]
    public string TDispatchVessel { get; set; }

    [Column("T_LABEL_PRINT_COUNT")]
    public int? TLabelPrintCount { get; set; }

    [Column("T_PREFIX_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string TPrefixId { get; set; }

    [Column("T_REQUEST_QUANTITY")]
    public int? TRequestQuantity { get; set; }

    [Column("T_REQUEST_SEQ_NO")]
    public int? TRequestSeqNo { get; set; }
}