// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_OOS_DISTR_ITEM")]
public partial class COosDistrItem
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Required]
    [Column("C_DISTRIBUTION_LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string CDistributionList { get; set; }

    [Required]
    [Column("TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Type { get; set; }

    [Required]
    [Column("EMAIL")]
    [StringLength(30)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("DATE_FROM", TypeName = "date")]
    public DateTime DateFrom { get; set; }

    [Column("DATE_TO", TypeName = "date")]
    public DateTime? DateTo { get; set; }

    [Column("CUSTOMER_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string CustomerSelection { get; set; }

    [Column("SAMPLINGPOINT_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string SamplingpointSelection { get; set; }

    [Column("SAMPLETYPE_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string SampletypeSelection { get; set; }

    [Column("MATRIX_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string MatrixSelection { get; set; }

    [Column("ANALYSIS_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string AnalysisSelection { get; set; }

    [Column("ANALYSISTYPE_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string AnalysistypeSelection { get; set; }

    [Column("MONTH_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string MonthSelection { get; set; }

    [Column("WEEK_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string WeekSelection { get; set; }

    [Column("MONTHDAY_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string MonthdaySelection { get; set; }

    [Column("WEEKDAY_SELECTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string WeekdaySelection { get; set; }

    [Column("DATE_CREATED", TypeName = "date")]
    public DateTime DateCreated { get; set; }

    [Required]
    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime ChangedOn { get; set; }

    [Column("ORDER_NUMBER")]
    public int OrderNumber { get; set; }
}