// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_OOS_DISTR_LIST")]
[Index("Name", Name = "idx_COOSDISTRLIST_NAME", IsUnique = true)]
public partial class COosDistrList
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("DEFAULT_SUBJECT")]
    [StringLength(100)]
    [Unicode(false)]
    public string DefaultSubject { get; set; }

    [Column("DEFAULT_TEXT")]
    [StringLength(500)]
    [Unicode(false)]
    public string DefaultText { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("DATE_CREATED", TypeName = "date")]
    public DateTime? DateCreated { get; set; }
}