// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_PACKAGE")]
public partial class CPackage
{
    [Key]
    [Column("NAME")]
    [StringLength(40)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("CUSTOMER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Customer { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("EXTERNAL_REFERENCE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ExternalReference { get; set; }

    [Column("TESTLIST_LINK")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestlistLink { get; set; }
}