// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_RESULT_SPEC")]
[Index("ResultNumber", "SpecSeqNum", Name = "idx_CRESULTSPEC", IsUnique = true)]
public partial class CResultSpec
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("RESULT_NUMBER")]
    public int ResultNumber { get; set; }

    [Column("SPEC_SEQ_NUM")]
    public int SpecSeqNum { get; set; }

    [Column("RESULT_VALUE")]
    [StringLength(254)]
    [Unicode(false)]
    public string ResultValue { get; set; }

    [Column("IN_SPEC")]
    [StringLength(1)]
    [Unicode(false)]
    public string InSpec { get; set; }

    [Column("SPEC_CODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SpecCode { get; set; }
}