// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_SAMPLE_PRIORITY")]
public partial class CSamplePriority
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("code")]
    public int Code { get; set; }

    [Column("description")]
    [StringLength(20)]
    [Unicode(false)]
    public string Description { get; set; }
}