// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_SCAN_DETAILS")]
[Index("SampleNumber", "PlateDetails", Name = "idxSCAN_DETAILS_SAMPLENO")]
public partial class CScanDetails
{
    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("SAMPLE_NUMBER")]
    public int SampleNumber { get; set; }

    [Column("PLATE_DETAILS")]
    public int? PlateDetails { get; set; }

    [Required]
    [Column("BARCODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("DUPLO")]
    [StringLength(2)]
    [Unicode(false)]
    public string Duplo { get; set; }

    [Column("SCAN_DATETIME", TypeName = "datetime")]
    public DateTime? ScanDatetime { get; set; }

    [Column("ENTRY")]
    [StringLength(254)]
    [Unicode(false)]
    public string Entry { get; set; }

    [Column("DATE_CREATED", TypeName = "date")]
    public DateTime? DateCreated { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("PRINTED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Printed { get; set; }

    [Column("TEST_NUMBER")]
    public int? TestNumber { get; set; }
}