// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects;

[Table("C_SPECIFICATIONS")]
public partial class CSpecifications
{
    [Required]
    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Column("VERSION")]
    public int Version { get; set; }

    [Required]
    [Column("COMPONENT")]
    [StringLength(60)]
    [Unicode(false)]
    public string Component { get; set; }

    [Required]
    [Column("TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Type { get; set; }

    [Required]
    [Column("TYPE_VALUE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TypeValue { get; set; }

    [Key]
    [Column("SEQ_NUM")]
    public int SeqNum { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("SPEC_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SpecType { get; set; }

    [Column("SPEC_RULE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SpecRule { get; set; }

    [Column("MINIMUM")]
    public double? Minimum { get; set; }

    [Column("MAXIMUM")]
    public double? Maximum { get; set; }

    [Column("TEXT_VALUE")]
    [StringLength(254)]
    [Unicode(false)]
    public string TextValue { get; set; }

    [Column("UNITS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Units { get; set; }

    [Column("AND_OR")]
    [StringLength(20)]
    [Unicode(false)]
    public string AndOr { get; set; }

    [Column("MAX_DEVIATION")]
    public int? MaxDeviation { get; set; }

    [Column("REFERENCE_RES_COUNT")]
    public int? ReferenceResCount { get; set; }

    [Required]
    [Column("SPEC_CODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SpecCode { get; set; }

    [Column("PRIORITY")]
    public int? Priority { get; set; }

    [Column("ACTIVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string Active { get; set; }

    [Column("EMAIL_RES_ENTERED")]
    [StringLength(254)]
    [Unicode(false)]
    public string EmailResEntered { get; set; }

    [Column("EMAIL_RES_APPROVED")]
    [StringLength(254)]
    [Unicode(false)]
    public string EmailResApproved { get; set; }

    [Column("EMAIL_TEST_APPROVED")]
    [StringLength(254)]
    [Unicode(false)]
    public string EmailTestApproved { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }
}