// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("CUSTOMER")]
[Index("CompanyName", Name = "idxCustomerCompany")]
public partial class Customer
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("COMPANY_NAME")]
    [StringLength(80)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    [Column("ADDRESS1")]
    [StringLength(78)]
    [Unicode(false)]
    public string Address1 { get; set; }

    [Column("ADDRESS2")]
    [StringLength(78)]
    [Unicode(false)]
    public string Address2 { get; set; }

    [Column("ADDRESS3")]
    [StringLength(78)]
    [Unicode(false)]
    public string Address3 { get; set; }

    [Column("ADDRESS4")]
    [StringLength(78)]
    [Unicode(false)]
    public string Address4 { get; set; }

    [Column("ADDRESS5")]
    [StringLength(78)]
    [Unicode(false)]
    public string Address5 { get; set; }

    [Column("ADDRESS6")]
    [StringLength(78)]
    [Unicode(false)]
    public string Address6 { get; set; }

    [Column("FAX_NUM")]
    [StringLength(20)]
    [Unicode(false)]
    public string FaxNum { get; set; }

    [Column("PHONE_NUM")]
    [StringLength(20)]
    [Unicode(false)]
    public string PhoneNum { get; set; }

    [Column("CONTACT")]
    [StringLength(78)]
    [Unicode(false)]
    public string Contact { get; set; }

    [Column("COST_FACTOR")]
    public float? CostFactor { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("REPORT_FORMAT")]
    [StringLength(50)]
    [Unicode(false)]
    public string ReportFormat { get; set; }

    [Column("EMAIL_ADDR")]
    [StringLength(150)]
    [Unicode(false)]
    public string EmailAddr { get; set; }

    [Column("RECORD_SET")]
    [StringLength(255)]
    [Unicode(false)]
    public string RecordSet { get; set; }

    [Column("T_BAD_DEBT")]
    [StringLength(1)]
    [Unicode(false)]
    public string TBadDebt { get; set; }

    [Column("T_CERT_FORMATS")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCertFormats { get; set; }

    [Column("T_COA_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCoaTemplate { get; set; }

    [Column("T_COVER_LETTER")]
    [StringLength(1)]
    [Unicode(false)]
    public string TCoverLetter { get; set; }

    [Column("T_CUSTOMER_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCustomerGroup { get; set; }

    [Column("T_EMAIL")]
    [StringLength(1)]
    [Unicode(false)]
    public string TEmail { get; set; }

    [Column("T_PO_REQUIRED")]
    [StringLength(1)]
    [Unicode(false)]
    public string TPoRequired { get; set; }

    [Column("T_PREPAY")]
    [StringLength(1)]
    [Unicode(false)]
    public string TPrepay { get; set; }

    [Column("T_PRINT")]
    [StringLength(1)]
    [Unicode(false)]
    public string TPrint { get; set; }

    [Column("T_PROSPECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string TProspect { get; set; }

    [Column("T_REPORT_TO")]
    public int? TReportTo { get; set; }

    [Column("T_TEST_LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TTestList { get; set; }

    [Column("T_VIEW_GROUP_DATA")]
    [StringLength(1)]
    [Unicode(false)]
    public string TViewGroupData { get; set; }

    [Column("T_WEB")]
    [StringLength(1)]
    [Unicode(false)]
    public string TWeb { get; set; }

    [Column("T_WEB_FOLDER")]
    [StringLength(255)]
    [Unicode(false)]
    public string TWebFolder { get; set; }

    [Column("T_RECEIPT_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TReceiptTemplate { get; set; }
}