// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("Instrument", "EventType", "EnteredOn")]
[Table("INSTRUMENT_LOG")]
[Index("Instrument", Name = "INSTRUMENT_LO13930")]
public partial class InstrumentLog
{
    [Key]
    [Column("INSTRUMENT")]
    [StringLength(20)]
    [Unicode(false)]
    public string Instrument { get; set; }

    [Key]
    [Column("EVENT_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string EventType { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("LOG_ENTRY", TypeName = "text")]
    public string LogEntry { get; set; }

    [Column("ENTERED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string EnteredBy { get; set; }

    [Key]
    [Column("ENTERED_ON", TypeName = "datetime")]
    public DateTime EnteredOn { get; set; }

    [Column("T_CALIB_INTV")]
    public int? TCalibIntv { get; set; }

    [Column("T_SAMPLE_NUMBER")]
    public int? TSampleNumber { get; set; }
}