// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("INSTRUMENTS")]
public partial class Instruments
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("INST_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string InstGroup { get; set; }

    [Column("ON_LINE")]
    [StringLength(1)]
    [Unicode(false)]
    public string OnLine { get; set; }

    [Column("LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string Location { get; set; }

    [Column("OPERATOR")]
    [StringLength(20)]
    [Unicode(false)]
    public string Operator { get; set; }

    [Column("VENDOR")]
    [StringLength(20)]
    [Unicode(false)]
    public string Vendor { get; set; }

    [Column("SERIAL_NO")]
    [StringLength(78)]
    [Unicode(false)]
    public string SerialNo { get; set; }

    [Column("PM_DATE", TypeName = "datetime")]
    public DateTime? PmDate { get; set; }

    [Column("PM_INTV")]
    public int? PmIntv { get; set; }

    [Column("PM_EXPIRATION", TypeName = "datetime")]
    public DateTime? PmExpiration { get; set; }

    [Column("CALIB_DATE", TypeName = "datetime")]
    public DateTime? CalibDate { get; set; }

    [Column("CALIB_INTV")]
    public int? CalibIntv { get; set; }

    [Column("CALIB_EXPIRATION", TypeName = "datetime")]
    public DateTime? CalibExpiration { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("LINK_LOCATION")]
    [StringLength(254)]
    [Unicode(false)]
    public string LinkLocation { get; set; }

    [Column("PARAMETER_1_NAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Parameter1Name { get; set; }

    [Column("PARAMETER_1_VALUE")]
    [StringLength(254)]
    [Unicode(false)]
    public string Parameter1Value { get; set; }

    [Column("PARAMETER_2_NAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Parameter2Name { get; set; }

    [Column("PARAMETER_2_VALUE")]
    [StringLength(254)]
    [Unicode(false)]
    public string Parameter2Value { get; set; }

    [Column("LABSTATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string Labstation { get; set; }

    [Column("BAUD")]
    [StringLength(10)]
    [Unicode(false)]
    public string Baud { get; set; }

    [Column("PARITY")]
    [StringLength(10)]
    [Unicode(false)]
    public string Parity { get; set; }

    [Column("STOP_BITS")]
    [StringLength(1)]
    [Unicode(false)]
    public string StopBits { get; set; }

    [Column("DATA_BITS")]
    [StringLength(5)]
    [Unicode(false)]
    public string DataBits { get; set; }

    [Column("FLOW_CONTROL")]
    [StringLength(20)]
    [Unicode(false)]
    public string FlowControl { get; set; }

    [Column("INSTRUMENT_CLASS")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstrumentClass { get; set; }

    [Column("LOW_THRESHOLD")]
    public float? LowThreshold { get; set; }

    [Column("HIGH_THRESHOLD")]
    public float? HighThreshold { get; set; }

    [Column("STABILITY_DELTA")]
    public float? StabilityDelta { get; set; }

    [Column("STABILITY_NUMBER")]
    public int? StabilityNumber { get; set; }

    [Column("PARENT_INSTRUMENT")]
    [StringLength(20)]
    [Unicode(false)]
    public string ParentInstrument { get; set; }

    [Column("INST_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string InstTemplate { get; set; }

    [Column("CALIB_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string CalibTemplate { get; set; }

    [Column("PM_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string PmTemplate { get; set; }

    [Column("SERVICE_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ServiceTemplate { get; set; }

    [Column("NEEDS_CALIBRATION")]
    [StringLength(1)]
    [Unicode(false)]
    public string NeedsCalibration { get; set; }

    [Column("NEEDS_PM")]
    [StringLength(1)]
    [Unicode(false)]
    public string NeedsPm { get; set; }

    [Column("IP_ADDRESS")]
    [StringLength(50)]
    [Unicode(false)]
    public string IpAddress { get; set; }

    [Column("PORT_NUMBER")]
    public int? PortNumber { get; set; }

    [Column("TERM_PATTERN")]
    [StringLength(50)]
    [Unicode(false)]
    public string TermPattern { get; set; }

    [Column("TIME_OUT")]
    public int? TimeOut { get; set; }

    [Column("XMIT_PREFIX")]
    [StringLength(50)]
    [Unicode(false)]
    public string XmitPrefix { get; set; }

    [Column("XMIT_SUFFIX")]
    [StringLength(50)]
    [Unicode(false)]
    public string XmitSuffix { get; set; }

    [Column("POLLING_TIME")]
    public int? PollingTime { get; set; }

    [Column("COMM_PORT")]
    [StringLength(20)]
    [Unicode(false)]
    public string CommPort { get; set; }

    [Column("HOLDS_SAMPLES")]
    [StringLength(1)]
    [Unicode(false)]
    public string HoldsSamples { get; set; }

    [Column("DATA_PATH")]
    [StringLength(254)]
    [Unicode(false)]
    public string DataPath { get; set; }

    [Column("DISCARD_TIME")]
    public int? DiscardTime { get; set; }

    [Column("FILTER_SCRIPT")]
    [StringLength(254)]
    [Unicode(false)]
    public string FilterScript { get; set; }

    [Column("PARSING_SCRIPT")]
    [StringLength(254)]
    [Unicode(false)]
    public string ParsingScript { get; set; }

    [Column("POST_ARCHIVE_ACTION")]
    [StringLength(20)]
    [Unicode(false)]
    public string PostArchiveAction { get; set; }

    [Column("SIZE_LIMIT")]
    public int? SizeLimit { get; set; }

    [Column("SYNC_PATTERN")]
    [StringLength(50)]
    [Unicode(false)]
    public string SyncPattern { get; set; }

    [Column("RENAME_EXT")]
    [StringLength(3)]
    [Unicode(false)]
    public string RenameExt { get; set; }

    [Column("SOURCE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Source { get; set; }

    [Column("STEP")]
    [StringLength(20)]
    [Unicode(false)]
    public string Step { get; set; }

    [Column("INCLUDE_SUBDIRS")]
    [StringLength(1)]
    [Unicode(false)]
    public string IncludeSubdirs { get; set; }

    [Column("FTP_USER")]
    [StringLength(50)]
    [Unicode(false)]
    public string FtpUser { get; set; }

    [Column("DEBUG")]
    [StringLength(1)]
    [Unicode(false)]
    public string Debug { get; set; }

    [Column("DIRECTORY")]
    [StringLength(254)]
    [Unicode(false)]
    public string Directory { get; set; }

    [Column("FTP_MODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string FtpMode { get; set; }

    [Column("PASSWORD")]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("STORE_IN_DB_FILE")]
    [StringLength(1)]
    [Unicode(false)]
    public string StoreInDbFile { get; set; }

    [Column("DB_FILE_PROMPT")]
    [StringLength(1)]
    [Unicode(false)]
    public string DbFilePrompt { get; set; }
}