// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("List", "Name")]
[Table("LIST_ENTRY")]
[Index("List", Name = "LIST_ENTRY_LIS8944")]
[Index("Name", Name = "LIST_ENTRY_NA14797")]
public partial class ListEntry
{
    [Key]
    [Column("LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string List { get; set; }

    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("VALUE")]
    [StringLength(254)]
    [Unicode(false)]
    public string Value { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }
}