// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("PERSON")]
[Index("AddressBook", Name = "PERSON_ADDRESS7446")]
[Index("Organization", Name = "idxPersonOrganization")]
public partial class Person
{
    [Key]
    [Column("PERSON_NUMBER")]
    public int PersonNumber { get; set; }

    [Column("ADDRESS_BOOK")]
    [StringLength(20)]
    [Unicode(false)]
    public string AddressBook { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("ALIAS")]
    [StringLength(30)]
    [Unicode(false)]
    public string Alias { get; set; }

    [Column("SALUTATION")]
    [StringLength(5)]
    [Unicode(false)]
    public string Salutation { get; set; }

    [Column("FIRST_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Column("MID_INIT")]
    [StringLength(5)]
    [Unicode(false)]
    public string MidInit { get; set; }

    [Column("LAST_NAME")]
    [StringLength(30)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("NAME_SUFX")]
    [StringLength(5)]
    [Unicode(false)]
    public string NameSufx { get; set; }

    [Column("TITLE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("ORGANIZATION")]
    [StringLength(40)]
    [Unicode(false)]
    public string Organization { get; set; }

    [Column("STREET_ADDR")]
    [StringLength(100)]
    [Unicode(false)]
    public string StreetAddr { get; set; }

    [Column("CITY")]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Column("STATE")]
    [StringLength(50)]
    [Unicode(false)]
    public string State { get; set; }

    [Column("COUNTRY")]
    [StringLength(20)]
    [Unicode(false)]
    public string Country { get; set; }

    [Column("ZIP")]
    [StringLength(10)]
    [Unicode(false)]
    public string Zip { get; set; }

    [Column("TEL_COUNTRY_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string TelCountryCode { get; set; }

    [Column("TEL_AREA_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string TelAreaCode { get; set; }

    [Column("PHONE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column("EXTENSION")]
    [StringLength(10)]
    [Unicode(false)]
    public string Extension { get; set; }

    [Column("CELL_AREA_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string CellAreaCode { get; set; }

    [Column("CELL_NUMBER")]
    [StringLength(20)]
    [Unicode(false)]
    public string CellNumber { get; set; }

    [Column("FAX_AREA_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string FaxAreaCode { get; set; }

    [Column("FAX_NUMBER")]
    [StringLength(20)]
    [Unicode(false)]
    public string FaxNumber { get; set; }

    [Column("FAX_EXTENSION")]
    [StringLength(10)]
    [Unicode(false)]
    public string FaxExtension { get; set; }

    [Column("BEEPER_AREA_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string BeeperAreaCode { get; set; }

    [Column("BEEPER_NUMBER")]
    [StringLength(20)]
    [Unicode(false)]
    public string BeeperNumber { get; set; }

    [Column("HOME_AREA_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string HomeAreaCode { get; set; }

    [Column("HOME_NUMBER")]
    [StringLength(20)]
    [Unicode(false)]
    public string HomeNumber { get; set; }

    [Column("EMAIL_ADDR")]
    [StringLength(100)]
    [Unicode(false)]
    public string EmailAddr { get; set; }

    [Column("PERSON_NOTE")]
    [StringLength(254)]
    [Unicode(false)]
    public string PersonNote { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("FULL_NAME")]
    [StringLength(60)]
    [Unicode(false)]
    public string FullName { get; set; }

    [Column("RELATES_TO")]
    public int? RelatesTo { get; set; }

    [Column("CONTACT_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ContactType { get; set; }

    [Column("FAX_COUNTRY_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string FaxCountryCode { get; set; }

    [Column("BEEPER_COUNTRY_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string BeeperCountryCode { get; set; }

    [Column("CELL_COUNTRY_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string CellCountryCode { get; set; }

    [Column("HOME_COUNTRY_CODE")]
    [StringLength(4)]
    [Unicode(false)]
    public string HomeCountryCode { get; set; }

    [Column("RECORD_SET")]
    [StringLength(254)]
    [Unicode(false)]
    public string RecordSet { get; set; }

    [Column("T_INVOICE_DELIVERY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TInvoiceDelivery { get; set; }

    [Column("T_INVOICE_PRIMARY")]
    [StringLength(1)]
    [Unicode(false)]
    public string TInvoicePrimary { get; set; }

    [Column("T_REPORT_DELIVERY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TReportDelivery { get; set; }

    [Column("T_REPORT_PRIMARY")]
    [StringLength(1)]
    [Unicode(false)]
    public string TReportPrimary { get; set; }

    [Column("T_RECEIPT_DELIVERY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TReceiptDelivery { get; set; }

    [Column("T_RECEIPT_PRIMARY")]
    [StringLength(1)]
    [Unicode(false)]
    public string TReceiptPrimary { get; set; }
}