// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("PROJECT")]
[Index("ChargeCode", Name = "idx_PROJECT_CHARGE_CODE")]
[Index("Customer", Name = "idx_Project_Customer")]
public partial class Project
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("TEMPLATE_VERSION")]
    public int? TemplateVersion { get; set; }

    [Column("TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Template { get; set; }

    [Column("TITLE")]
    [StringLength(30)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("NOTE")]
    [StringLength(254)]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("STATUS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("OLD_STATUS")]
    [StringLength(20)]
    [Unicode(false)]
    public string OldStatus { get; set; }

    [Column("DATE_CREATED", TypeName = "datetime")]
    public DateTime? DateCreated { get; set; }

    [Column("DATE_RECEIVED", TypeName = "datetime")]
    public DateTime? DateReceived { get; set; }

    [Column("DATE_STARTED", TypeName = "datetime")]
    public DateTime? DateStarted { get; set; }

    [Column("DATE_COMPLETED", TypeName = "datetime")]
    public DateTime? DateCompleted { get; set; }

    [Column("DATE_REVIEWED", TypeName = "datetime")]
    public DateTime? DateReviewed { get; set; }

    [Column("DATE_UPDATED", TypeName = "datetime")]
    public DateTime? DateUpdated { get; set; }

    [Column("COST_FACTOR")]
    public float? CostFactor { get; set; }

    [Column("CUSTOMER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Customer { get; set; }

    [Column("CUSTOMER_CONTACT")]
    [StringLength(40)]
    [Unicode(false)]
    public string CustomerContact { get; set; }

    [Column("OWNER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Owner { get; set; }

    [Column("CREATED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column("NUM_SAMPLES")]
    public int? NumSamples { get; set; }

    [Column("NUM_U")]
    public int? NumU { get; set; }

    [Column("NUM_I")]
    public int? NumI { get; set; }

    [Column("NUM_P")]
    public int? NumP { get; set; }

    [Column("NUM_C")]
    public int? NumC { get; set; }

    [Column("NUM_A")]
    public int? NumA { get; set; }

    [Column("NUM_R")]
    public int? NumR { get; set; }

    [Column("NUM_X")]
    public int? NumX { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("CLOSED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Closed { get; set; }

    [Column("SAMPLE_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SampleTemplate { get; set; }

    [Column("CONCLUSION")]
    [StringLength(10)]
    [Unicode(false)]
    public string Conclusion { get; set; }

    [Column("PRODUCT")]
    [StringLength(50)]
    [Unicode(false)]
    public string Product { get; set; }

    [Column("STABILITY")]
    [StringLength(1)]
    [Unicode(false)]
    public string Stability { get; set; }

    [Column("CHARGE_CODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChargeCode { get; set; }

    [Column("USE_GROUP_LOGIN")]
    [StringLength(1)]
    [Unicode(false)]
    public string UseGroupLogin { get; set; }

    [Column("BATCH_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string BatchTemplate { get; set; }

    [Column("USE_GRID_LOGIN")]
    [StringLength(1)]
    [Unicode(false)]
    public string UseGridLogin { get; set; }

    [Column("CUSTOMER_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string CustomerTemplate { get; set; }

    [Column("OWNER_LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string OwnerLocation { get; set; }

    [Column("ALIQUOT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Aliquot { get; set; }

    [Column("SIGNED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Signed { get; set; }

    [Column("T_CERTIFICATION")]
    [StringLength(30)]
    [Unicode(false)]
    public string TCertification { get; set; }

    [Column("T_CLOSED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TClosedBy { get; set; }

    [Column("T_CLOSED_ON", TypeName = "datetime")]
    public DateTime? TClosedOn { get; set; }

    [Column("T_COA_COMMENT")]
    public int? TCoaComment { get; set; }

    [Column("T_COA_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCoaTemplate { get; set; }

    [Column("T_CONTRACT_NUMBER")]
    [StringLength(10)]
    [Unicode(false)]
    public string TContractNumber { get; set; }

    [Column("T_COPY_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCopyTemplate { get; set; }

    [Column("T_CUST_MANIFEST")]
    [StringLength(254)]
    [Unicode(false)]
    public string TCustManifest { get; set; }

    [Column("T_CUSTOMER_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCustomerGroup { get; set; }

    [Column("T_INVOICE_NUMBER")]
    public int? TInvoiceNumber { get; set; }

    [Column("T_LOGIN_VERIF_REQD")]
    [StringLength(1)]
    [Unicode(false)]
    public string TLoginVerifReqd { get; set; }

    [Column("T_LOGIN_VERIFIED")]
    [StringLength(1)]
    [Unicode(false)]
    public string TLoginVerified { get; set; }

    [Column("T_LOGIN_VERIFIED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TLoginVerifiedBy { get; set; }

    [Column("T_LOGIN_VERIFIED_ON", TypeName = "datetime")]
    public DateTime? TLoginVerifiedOn { get; set; }

    [Column("T_NOTE")]
    public int? TNote { get; set; }

    [Column("T_PO_NUMBER")]
    [StringLength(40)]
    [Unicode(false)]
    public string TPoNumber { get; set; }

    [Column("T_SOURCE_CUSTOMER")]
    [StringLength(20)]
    [Unicode(false)]
    public string TSourceCustomer { get; set; }

    [Column("T_PRE_INVOICE_NUMBER")]
    public int? TPreInvoiceNumber { get; set; }

    [Column("T_PRIORITY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TPriority { get; set; }

    [Column("T_STATUS")]
    [StringLength(254)]
    [Unicode(false)]
    public string TStatus { get; set; }

    [Column("T_ZERO_TEST_CHARGE")]
    [StringLength(1)]
    [Unicode(false)]
    public string TZeroTestCharge { get; set; }

    [Column("T_COA_COMPLETE")]
    [StringLength(1)]
    [Unicode(false)]
    public string TCoaComplete { get; set; }

    [Column("T_CATALOGUE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TCatalogue { get; set; }

    [Column("T_CATALOGUE_VERSION")]
    public int? TCatalogueVersion { get; set; }

    [Column("T_RECEIPT_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string TReceiptTemplate { get; set; }

    [Column("FACILITY")]
    [StringLength(20)]
    [Unicode(false)]
    public string Facility { get; set; }

    [Column("T_COA_REQ")]
    [StringLength(1)]
    [Unicode(false)]
    public string TCoaReq { get; set; }

    [Column("T_INVOICE_REQ")]
    [StringLength(1)]
    [Unicode(false)]
    public string TInvoiceReq { get; set; }

    [Column("T_CONTACTS_REQ")]
    [StringLength(1)]
    [Unicode(false)]
    public string TContactsReq { get; set; }

    [Column("T_END_PERIOD", TypeName = "datetime")]
    public DateTime? TEndPeriod { get; set; }

    [Column("T_PROGRAM")]
    [StringLength(30)]
    [Unicode(false)]
    public string TProgram { get; set; }

    [Column("T_START_PERIOD", TypeName = "datetime")]
    public DateTime? TStartPeriod { get; set; }

    [Column("C_EXTERNAL_REFERENCE")]
    [StringLength(50)]
    [Unicode(false)]
    public string CExternalReference { get; set; }

    [Column("C_SAMPLING_BY")]
    [StringLength(30)]
    [Unicode(false)]
    public string CSamplingBy { get; set; }

    [Column("C_LANGUAGE")]
    [StringLength(20)]
    [Unicode(false)]
    public string CLanguage { get; set; }

    [Column("C_FIXEDPRICE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CFixedprice { get; set; }

    [Column("C_FIXEDAMOUNT", TypeName = "decimal(18, 2)")]
    public decimal? CFixedamount { get; set; }

    [Column("C_EMAILTO")]
    [StringLength(80)]
    public string CEmailto { get; set; }

    [Column("C_REPORTS_TO")]
    [StringLength(80)]
    public string CReportsTo { get; set; }

    [Column("C_INVOICE_TO")]
    [StringLength(80)]
    public string CInvoiceTo { get; set; }
}