// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("Name", "ChangedOn")]
[Table("QC_SAMPLES")]
public partial class QcSamples
{
    [Key]
    [Column("NAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Key]
    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("QC_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string QcType { get; set; }

    [Column("SAMPLE_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SampleTemplate { get; set; }

    [Column("TEST_LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestList { get; set; }

    [Column("ADD_BATCH_ANALYSES")]
    [StringLength(1)]
    [Unicode(false)]
    public string AddBatchAnalyses { get; set; }

    [Column("IS_PARENT")]
    [StringLength(1)]
    [Unicode(false)]
    public string IsParent { get; set; }

    [Column("IS_CHILD")]
    [StringLength(1)]
    [Unicode(false)]
    public string IsChild { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Column("COMPONENT")]
    [StringLength(60)]
    [Unicode(false)]
    public string Component { get; set; }
}