// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("REPORTS")]
public partial class Reports
{
    [Key]
    [Column("REPORT_NUMBER")]
    public int ReportNumber { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("REPORT_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ReportType { get; set; }

    [Column("PURPOSE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Purpose { get; set; }

    [Column("OBJECT_CLASS")]
    [StringLength(20)]
    [Unicode(false)]
    public string ObjectClass { get; set; }

    [Column("DATE_CREATED", TypeName = "datetime")]
    public DateTime? DateCreated { get; set; }

    [Column("CREATED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column("PRINT_COUNT")]
    public int? PrintCount { get; set; }

    [Column("DATA_CHANGED")]
    [StringLength(1)]
    [Unicode(false)]
    public string DataChanged { get; set; }

    [Column("RESULTS_CHANGED")]
    [StringLength(1)]
    [Unicode(false)]
    public string ResultsChanged { get; set; }

    [Column("REPORT_FILE_NAME")]
    [StringLength(254)]
    [Unicode(false)]
    public string ReportFileName { get; set; }

    [Column("SUPERSEDED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Superseded { get; set; }

    [Column("SUPERSEDED_BY")]
    public int? SupersededBy { get; set; }

    [Column("ALLOW_EDIT")]
    [StringLength(1)]
    [Unicode(false)]
    public string AllowEdit { get; set; }

    [Column("ALLOW_PRINT")]
    [StringLength(1)]
    [Unicode(false)]
    public string AllowPrint { get; set; }

    [Column("REPORT_STATUS")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReportStatus { get; set; }

    [Column("FAILURE_REASON")]
    [StringLength(254)]
    [Unicode(false)]
    public string FailureReason { get; set; }

    [Column("ALLOW_WEB_VIEW")]
    [StringLength(1)]
    [Unicode(false)]
    public string AllowWebView { get; set; }

    [Column("C_REASON_RECREATED")]
    [StringLength(254)]
    public string CReasonRecreated { get; set; }
}