// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("SAMPLING_POINT")]
[Index("CCustomer", Name = "idxSamplingPointCustomer")]
public partial class SamplingPoint
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("TEST_LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestList { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("PRIMARY_DISP_REQ")]
    [StringLength(1)]
    [Unicode(false)]
    public string PrimaryDispReq { get; set; }

    [Column("SECONDARY_DISP_REQ")]
    [StringLength(1)]
    [Unicode(false)]
    public string SecondaryDispReq { get; set; }

    [Column("T_LAB")]
    [StringLength(20)]
    [Unicode(false)]
    public string TLab { get; set; }

    [Column("T_LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string TLocation { get; set; }

    [Column("PRIMARY_RUN")]
    [StringLength(20)]
    [Unicode(false)]
    public string PrimaryRun { get; set; }

    [Column("SECONDARY_RUN")]
    [StringLength(20)]
    [Unicode(false)]
    public string SecondaryRun { get; set; }

    [Column("TERTIARY_RUN")]
    [StringLength(20)]
    [Unicode(false)]
    public string TertiaryRun { get; set; }

    [Column("SAMPLER_ID")]
    [StringLength(20)]
    [Unicode(false)]
    public string SamplerId { get; set; }

    [Column("SERVICE_RESERVOIR")]
    [StringLength(20)]
    [Unicode(false)]
    public string ServiceReservoir { get; set; }

    [Column("TREATMENT_WORKS")]
    [StringLength(20)]
    [Unicode(false)]
    public string TreatmentWorks { get; set; }

    [Column("ZONE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Zone { get; set; }

    [Column("WATER_SOURCE")]
    [StringLength(20)]
    [Unicode(false)]
    public string WaterSource { get; set; }

    [Column("SAMPLE_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SampleTemplate { get; set; }

    [Column("T_COLLECTION_NOTES")]
    public int? TCollectionNotes { get; set; }

    [Column("T_MAP_ZOOM")]
    [StringLength(20)]
    [Unicode(false)]
    public string TMapZoom { get; set; }

    [Column("T_PHOTO")]
    [StringLength(255)]
    [Unicode(false)]
    public string TPhoto { get; set; }

    [Column("T_UTM_LATITUDE")]
    public float? TUtmLatitude { get; set; }

    [Column("T_UTM_LONGITUDE")]
    public float? TUtmLongitude { get; set; }

    [Column("C_CUSTOMER")]
    [StringLength(20)]
    [Unicode(false)]
    public string CCustomer { get; set; }

    [Column("C_SAMPLE_TYPE")]
    [StringLength(10)]
    [Unicode(false)]
    public string CSampleType { get; set; }

    [Column("T_LATLONG")]
    [StringLength(40)]
    [Unicode(false)]
    public string TLatlong { get; set; }
}