// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("SAMPLE_RULES")]
public partial class SampleRules
{
    [Key]
    [Column("ENTRY_CODE")]
    public int EntryCode { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Column("VARIATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string Variation { get; set; }

    [Column("SAMPLE_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SampleType { get; set; }

    [Column("CONTAINER_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ContainerType { get; set; }

    [Column("COLLECTION_METHOD")]
    [StringLength(20)]
    [Unicode(false)]
    public string CollectionMethod { get; set; }

    [Column("STORAGE_CONDITION")]
    [StringLength(20)]
    [Unicode(false)]
    public string StorageCondition { get; set; }

    [Column("TEST_LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestList { get; set; }

    [Column("CONTRACT_NUMBER")]
    [StringLength(10)]
    [Unicode(false)]
    public string ContractNumber { get; set; }

    [Column("CUSTOMER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Customer { get; set; }

    [Column("PRODUCT")]
    [StringLength(50)]
    [Unicode(false)]
    public string Product { get; set; }

    [Column("T_CONTRACT_TESTS")]
    [StringLength(1)]
    [Unicode(false)]
    public string TContractTests { get; set; }

    [Column("JUISTE_FLES")]
    [StringLength(1)]
    [Unicode(false)]
    public string JuisteFles { get; set; }
}