// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("ItemId", "TDistributionList", "Person")]
[Table("T_DISTRIBUTION_ITEM")]
public partial class TDistributionItem
{
    [Key]
    [Column("ITEM_ID")]
    public int ItemId { get; set; }

    [Key]
    [Column("T_DISTRIBUTION_LIST")]
    [StringLength(30)]
    [Unicode(false)]
    public string TDistributionList { get; set; }

    [Key]
    [Column("PERSON")]
    public int Person { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("PERSON_NAME")]
    [StringLength(60)]
    [Unicode(false)]
    public string PersonName { get; set; }

    [Column("REPORT_PRIMARY")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReportPrimary { get; set; }

    [Column("REPORT_DELIVERY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ReportDelivery { get; set; }

    [Column("INVOICE_PRIMARY")]
    [StringLength(1)]
    [Unicode(false)]
    public string InvoicePrimary { get; set; }

    [Column("INVOICE_DELIVERY")]
    [StringLength(20)]
    [Unicode(false)]
    public string InvoiceDelivery { get; set; }

    [Column("RECEIPT_PRIMARY")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReceiptPrimary { get; set; }

    [Column("RECEIPT_DELIVERY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ReceiptDelivery { get; set; }
}