// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("Name", "Analysis", "AnalysisCount")]
[Table("TEST_LIST_ENTRY")]
[Index("Analysis", Name = "idx_TEST_LIST_ENTRY_ANALYSIS")]
public partial class TestListEntry
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Key]
    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("STD_TEST")]
    [StringLength(1)]
    [Unicode(false)]
    public string StdTest { get; set; }

    [Column("REPLICATE_COUNT")]
    public int? ReplicateCount { get; set; }

    [Column("PARAMETER_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string ParameterName { get; set; }

    [Column("PARAMETER_VALUE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ParameterValue { get; set; }

    [Column("TEST_PRIORITY")]
    public int? TestPriority { get; set; }

    [Column("INSTRUMENT")]
    [StringLength(20)]
    [Unicode(false)]
    public string Instrument { get; set; }

    [Column("TEST_LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestLocation { get; set; }

    [Column("ASSIGN_IF_PRESENT")]
    [StringLength(1)]
    [Unicode(false)]
    public string AssignIfPresent { get; set; }

    [Column("VARIATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string Variation { get; set; }

    [Key]
    [Column("ANALYSIS_COUNT")]
    public int AnalysisCount { get; set; }

    [Column("REPORTED_NAME")]
    [StringLength(30)]
    [Unicode(false)]
    public string ReportedName { get; set; }

    [Column("REPORTED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Reported { get; set; }

    [Column("COLLECTION_OFFSET")]
    public int? CollectionOffset { get; set; }

    [Column("T_PREP_ANALYSIS")]
    [StringLength(30)]
    [Unicode(false)]
    public string TPrepAnalysis { get; set; }

    [Column("METHOD")]
    [StringLength(50)]
    [Unicode(false)]
    public string Method { get; set; }
}