// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("TEST_LIST")]
public partial class TestList
{
    [Key]
    [Column("NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("GLOBAL_FLAG")]
    [StringLength(1)]
    [Unicode(false)]
    public string GlobalFlag { get; set; }

    [Column("OWNER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Owner { get; set; }

    [Column("SET_RSLT_ORDER_NO")]
    [StringLength(1)]
    [Unicode(false)]
    public string SetRsltOrderNo { get; set; }

    [Column("APPROVAL_ROLE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ApprovalRole { get; set; }

    [Column("T_ALLOWED_PRODUCT")]
    [StringLength(255)]
    [Unicode(false)]
    public string TAllowedProduct { get; set; }

    [Column("T_ALLOWED_SAM_TYPE")]
    [StringLength(255)]
    [Unicode(false)]
    public string TAllowedSamType { get; set; }

    [Column("T_PREREQ_CLEAR_STATUS")]
    [StringLength(20)]
    [Unicode(false)]
    public string TPrereqClearStatus { get; set; }

    [Column("C_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string CType { get; set; }

    [Column("C_PACKAGE")]
    [StringLength(40)]
    [Unicode(false)]
    public string CPackage { get; set; }
}