// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("TEST")]
[Index("Analysis", Name = "idxTEST_ANALYSIS")]
[Index("Batch", Name = "idxTEST_BATCH")]
[Index("PreInvoiceNumber", "Status", Name = "idxTEST_PREINVOICE")]
[Index("SampleNumber", Name = "idxTEST_SAMPLENUMBER")]
[Index("Status", Name = "ridxTEST_STATUS")]
public partial class Test
{
    [Column("SAMPLE_NUMBER")]
    public int? SampleNumber { get; set; }

    [Key]
    [Column("TEST_NUMBER")]
    public int TestNumber { get; set; }

    [Column("ORDER_NUMBER")]
    public int? OrderNumber { get; set; }

    [Column("ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Analysis { get; set; }

    [Column("VERSION")]
    public int? Version { get; set; }

    [Column("ANALYSIS_COUNT")]
    public int? AnalysisCount { get; set; }

    [Column("VARIATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string Variation { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("REPORTED_NAME")]
    [StringLength(30)]
    [Unicode(false)]
    public string ReportedName { get; set; }

    [Column("REPLICATE_COUNT")]
    public int? ReplicateCount { get; set; }

    [Column("STATUS")]
    [StringLength(1)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("OLD_STATUS")]
    [StringLength(1)]
    [Unicode(false)]
    public string OldStatus { get; set; }

    [Column("BATCH_PARENT_TEST")]
    public int? BatchParentTest { get; set; }

    [Column("BATCH_SIBLING_TEST")]
    public int? BatchSiblingTest { get; set; }

    [Column("PARENT_TEST")]
    public int? ParentTest { get; set; }

    [Column("ORIGINAL_TEST")]
    public int? OriginalTest { get; set; }

    [Column("DATE_RECEIVED", TypeName = "datetime")]
    public DateTime? DateReceived { get; set; }

    [Column("DATE_STARTED", TypeName = "datetime")]
    public DateTime? DateStarted { get; set; }

    [Column("ASSIGNED_OPERATOR")]
    [StringLength(20)]
    [Unicode(false)]
    public string AssignedOperator { get; set; }

    [Column("PREP")]
    [StringLength(1)]
    [Unicode(false)]
    public string Prep { get; set; }

    [Column("PREP_DATE", TypeName = "datetime")]
    public DateTime? PrepDate { get; set; }

    [Column("PREP_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string PrepBy { get; set; }

    [Column("DATE_COMPLETED", TypeName = "datetime")]
    public DateTime? DateCompleted { get; set; }

    [Column("DATE_REVIEWED", TypeName = "datetime")]
    public DateTime? DateReviewed { get; set; }

    [Column("REVIEWER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Reviewer { get; set; }

    [Column("REPLICATE_TEST")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReplicateTest { get; set; }

    [Column("INSTRUMENT")]
    [StringLength(20)]
    [Unicode(false)]
    public string Instrument { get; set; }

    [Column("TEST_PRIORITY")]
    public int? TestPriority { get; set; }

    [Column("IN_SPEC")]
    [StringLength(1)]
    [Unicode(false)]
    public string InSpec { get; set; }

    [Column("IN_CAL")]
    [StringLength(1)]
    [Unicode(false)]
    public string InCal { get; set; }

    [Column("TEST_COMMENT")]
    [StringLength(254)]
    [Unicode(false)]
    public string TestComment { get; set; }

    [Column("TEST_LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestLocation { get; set; }

    [Column("PARAMETER_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string ParameterName { get; set; }

    [Column("PARAMETER_VALUE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ParameterValue { get; set; }

    [Column("EXPECTED_DATE", TypeName = "datetime")]
    public DateTime? ExpectedDate { get; set; }

    [Column("LAB")]
    [StringLength(20)]
    [Unicode(false)]
    public string Lab { get; set; }

    [Column("RESOLVE_REQD")]
    [StringLength(1)]
    [Unicode(false)]
    public string ResolveReqd { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("STAGE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Stage { get; set; }

    [Column("PRIMARY_IN_SPEC")]
    [StringLength(1)]
    [Unicode(false)]
    public string PrimaryInSpec { get; set; }

    [Column("BATCH")]
    [StringLength(20)]
    [Unicode(false)]
    public string Batch { get; set; }

    [Column("IN_CONTROL")]
    [StringLength(1)]
    [Unicode(false)]
    public string InControl { get; set; }

    [Column("TEST_LIST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TestList { get; set; }

    [Column("RE_TESTED")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReTested { get; set; }

    [Column("MODIFIED_RESULTS")]
    [StringLength(1)]
    [Unicode(false)]
    public string ModifiedResults { get; set; }

    [Column("ALIQUOTED_TO")]
    public int? AliquotedTo { get; set; }

    [Column("ON_WORKSHEET")]
    [StringLength(1)]
    [Unicode(false)]
    public string OnWorksheet { get; set; }

    [Column("DISP_FLDS")]
    [StringLength(20)]
    [Unicode(false)]
    public string DispFlds { get; set; }

    [Column("DISPLAY_RESULTS")]
    [StringLength(1)]
    [Unicode(false)]
    public string DisplayResults { get; set; }

    [Column("ALIQUOT_GROUP")]
    [StringLength(100)]
    [Unicode(false)]
    public string AliquotGroup { get; set; }

    [Column("SPLIT_REPLICATES")]
    [StringLength(1)]
    [Unicode(false)]
    public string SplitReplicates { get; set; }

    [Column("CROSS_SAMPLE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CrossSample { get; set; }

    [Column("RELEASED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Released { get; set; }

    [Column("RELEASED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ReleasedBy { get; set; }

    [Column("RELEASED_ON", TypeName = "datetime")]
    public DateTime? ReleasedOn { get; set; }

    [Column("RELEASE_COMMENT")]
    [StringLength(254)]
    [Unicode(false)]
    public string ReleaseComment { get; set; }

    [Column("DOUBLE_ENTRY")]
    [StringLength(1)]
    [Unicode(false)]
    public string DoubleEntry { get; set; }

    [Column("CHILD_OUT_SPEC")]
    [StringLength(1)]
    [Unicode(false)]
    public string ChildOutSpec { get; set; }

    [Column("CHARGE_ENTRY")]
    public int? ChargeEntry { get; set; }

    [Column("SIGNED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Signed { get; set; }

    [Column("BATCH_ORIGINAL_TEST")]
    public int? BatchOriginalTest { get; set; }

    [Column("TEST_SEQUENCE_NO")]
    public int? TestSequenceNo { get; set; }

    [Column("INVOICE_NUMBER")]
    public int? InvoiceNumber { get; set; }

    [Column("BILLING_ITEM_DESC")]
    [StringLength(50)]
    [Unicode(false)]
    public string BillingItemDesc { get; set; }

    [Column("CNTRCT_QTE_ITEM_NO")]
    public int? CntrctQteItemNo { get; set; }

    [Column("REPORTED_RSLT_OOS")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReportedRsltOos { get; set; }

    [Column("CONTAINER_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ContainerType { get; set; }

    [Column("DOUBLE_BLIND")]
    [StringLength(1)]
    [Unicode(false)]
    public string DoubleBlind { get; set; }

    [Column("PRE_INVOICE_NUMBER")]
    public int? PreInvoiceNumber { get; set; }

    [Column("T_ALLOWED_PRODUCT")]
    [StringLength(255)]
    [Unicode(false)]
    public string TAllowedProduct { get; set; }

    [Column("T_ALLOWED_SAM_TYPE")]
    [StringLength(255)]
    [Unicode(false)]
    public string TAllowedSamType { get; set; }

    [Column("T_ANALYSIS_METHOD")]
    [StringLength(30)]
    [Unicode(false)]
    public string TAnalysisMethod { get; set; }

    [Column("T_CHARGE_GROUP")]
    public int? TChargeGroup { get; set; }

    [Column("T_CLIENT_DUE_DATE", TypeName = "datetime")]
    public DateTime? TClientDueDate { get; set; }

    [Column("T_CLIENT_PRIORITY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TClientPriority { get; set; }

    [Column("T_CLIENT_TURNARUND")]
    [StringLength(50)]
    [Unicode(false)]
    public string TClientTurnarund { get; set; }

    [Column("T_CONTAINER_GROUP")]
    [StringLength(20)]
    [Unicode(false)]
    public string TContainerGroup { get; set; }

    [Column("T_DATE_ENABLED", TypeName = "datetime")]
    public DateTime? TDateEnabled { get; set; }

    [Column("T_INST_TESTS")]
    [StringLength(254)]
    [Unicode(false)]
    public string TInstTests { get; set; }

    [Column("T_LAB_DUE_DATE", TypeName = "datetime")]
    public DateTime? TLabDueDate { get; set; }

    [Column("T_PREP_ANALYSIS")]
    [StringLength(20)]
    [Unicode(false)]
    public string TPrepAnalysis { get; set; }

    [Column("T_PREP_ANALYSIS_GRP")]
    [StringLength(20)]
    [Unicode(false)]
    public string TPrepAnalysisGrp { get; set; }

    [Column("T_PREP_TEST")]
    public int? TPrepTest { get; set; }

    [Column("T_QC_REFERENCE")]
    public int? TQcReference { get; set; }

    [Column("T_REPORT_HEADER")]
    [StringLength(20)]
    [Unicode(false)]
    public string TReportHeader { get; set; }

    [Column("T_TURNAROUND_ACTUA")]
    public int? TTurnaroundActua { get; set; }

    [Column("T_TURNAROUND_CHARG")]
    public int? TTurnaroundCharg { get; set; }

    [Column("T_TURNAROUND_MET")]
    [StringLength(1)]
    [Unicode(false)]
    public string TTurnaroundMet { get; set; }

    [Column("ANALYSIS_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string AnalysisType { get; set; }

    [Column("COMMON_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string CommonName { get; set; }

    [Column("T_INVOICE_TEST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TInvoiceTest { get; set; }

    [Column("T_SHIP_REQUEST")]
    [StringLength(20)]
    [Unicode(false)]
    public string TShipRequest { get; set; }

    [Column("ANSWER_SET")]
    public int? AnswerSet { get; set; }

    [Column("T_REPORT_GROUP")]
    [StringLength(50)]
    [Unicode(false)]
    public string TReportGroup { get; set; }

    [Column("T_PREREQ_CLEARED")]
    [StringLength(1)]
    [Unicode(false)]
    public string TPrereqCleared { get; set; }

    [Column("T_FACILITY")]
    [StringLength(20)]
    [Unicode(false)]
    public string TFacility { get; set; }

    [Column("T_NEEDS_FACILITY")]
    [StringLength(1)]
    [Unicode(false)]
    public string TNeedsFacility { get; set; }

    [Column("LAB_TYPE")]
    [StringLength(20)]
    [Unicode(false)]
    public string LabType { get; set; }

    [Column("REQD_VOLUME")]
    public int? ReqdVolume { get; set; }

    [Column("T_NORMAL_CONTAINER")]
    [StringLength(20)]
    [Unicode(false)]
    public string TNormalContainer { get; set; }

    [Column("C_DISCLAIMER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CDisclaimer { get; set; }

    [Column("C_PACKAGE")]
    [StringLength(20)]
    [Unicode(false)]
    public string CPackage { get; set; }

    [Column("AUDIT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Audit { get; set; }

    [Column("METHOD")]
    [StringLength(50)]
    [Unicode(false)]
    public string Method { get; set; }

    [Column("METHOD_VERSION")]
    public int? MethodVersion { get; set; }

    [Column("C_CONSERVATION_TIME")]
    public int? CConservationTime { get; set; }
}