// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("T_PROGRAM")]
public partial class TProgram
{
    [Key]
    [Column("NAME")]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("FIRST_DAY_OF_WEEK")]
    [StringLength(20)]
    [Unicode(false)]
    public string FirstDayOfWeek { get; set; }

    [Column("TREAT_HOLIDAYS_AS")]
    [StringLength(20)]
    [Unicode(false)]
    public string TreatHolidaysAs { get; set; }

    [Column("NEEDS_RELOADING")]
    [StringLength(1)]
    [Unicode(false)]
    public string NeedsReloading { get; set; }

    [Column("WORKSTATION")]
    [StringLength(30)]
    [Unicode(false)]
    public string Workstation { get; set; }

    [Column("RUNNING")]
    [StringLength(1)]
    [Unicode(false)]
    public string Running { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("GUI_CONFIG", TypeName = "text")]
    public string GuiConfig { get; set; }

    [Column("CUSTOMER")]
    [StringLength(20)]
    [Unicode(false)]
    public string Customer { get; set; }

    [Column("START_DATE", TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column("END_DATE", TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column("CONTRACT_NUMBER")]
    public int? ContractNumber { get; set; }

    [Column("STATUS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("WS_INSERT_DATE", TypeName = "datetime")]
    public DateTime? WsInsertDate { get; set; }

    [Column("REPORT_FREQUENCY")]
    public int? ReportFrequency { get; set; }

    [Column("PROJECT_TEMPLATE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ProjectTemplate { get; set; }

    [Column("RELOAD_WATER_SCHED")]
    [StringLength(1)]
    [Unicode(false)]
    public string ReloadWaterSched { get; set; }

    [Column("WS_LAST_DATE", TypeName = "datetime")]
    public DateTime? WsLastDate { get; set; }

    [Column("DATAFILE")]
    [StringLength(255)]
    [Unicode(false)]
    public string Datafile { get; set; }

    [Column("VALIDATION_MSG")]
    public int? ValidationMsg { get; set; }

    [Column("ERROR_MSG")]
    public int? ErrorMsg { get; set; }
}