// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("TProgram", "OrderNumber")]
[Table("T_PROGRAM_ITEM")]
[Index("Product", Name = "idx_T_PROGRAM_ITEM_PRODUCT")]
[Index("SamplingPoint", Name = "idx_T_PROGRAM_ITEM_SAMPLING_POINT")]
[Index("Season", Name = "idx_T_PROGRAM_ITEM_SEASON")]
[Index("TestList", Name = "idx_T_PROGRAM_ITEM_TEST_LIST")]
[Index("TProgram", Name = "idx_T_PROGRAM_ITEM_T_PROGRAM")]
public partial class TProgramItem
{
    [Key]
    [Column("T_PROGRAM")]
    [StringLength(30)]
    [Unicode(false)]
    public string TProgram { get; set; }

    [Key]
    [Column("ORDER_NUMBER")]
    public int OrderNumber { get; set; }

    [Column("LOGIN_OFFSET")]
    public int? LoginOffset { get; set; }

    [Column("SAMPLING_POINT")]
    [StringLength(50)]
    [Unicode(false)]
    public string SamplingPoint { get; set; }

    [Column("C_PACKAGE")]
    [StringLength(255)]
    [Unicode(false)]
    public string CPackage { get; set; }

    [Column("TEST_LIST")]
    [StringLength(255)]
    [Unicode(false)]
    public string TestList { get; set; }

    [Column("ANALYSES")]
    [StringLength(255)]
    [Unicode(false)]
    public string Analyses { get; set; }

    [Column("PRODUCT")]
    [StringLength(20)]
    [Unicode(false)]
    public string Product { get; set; }

    [Column("PRODUCT_GRADE")]
    [StringLength(20)]
    [Unicode(false)]
    public string ProductGrade { get; set; }

    [Column("SEASON")]
    [StringLength(20)]
    [Unicode(false)]
    public string Season { get; set; }

    [Column("MON_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string MonCollect { get; set; }

    [Column("TUES_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string TuesCollect { get; set; }

    [Column("WED_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string WedCollect { get; set; }

    [Column("THURS_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string ThursCollect { get; set; }

    [Column("FRI_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string FriCollect { get; set; }

    [Column("SAT_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string SatCollect { get; set; }

    [Column("SUN_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string SunCollect { get; set; }

    [Column("WK_1_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Wk1Collect { get; set; }

    [Column("WK_2_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Wk2Collect { get; set; }

    [Column("WK_3_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Wk3Collect { get; set; }

    [Column("WK_4_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Wk4Collect { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("LAST_RUN", TypeName = "datetime")]
    public DateTime? LastRun { get; set; }

    [Column("RUNNING")]
    [StringLength(1)]
    [Unicode(false)]
    public string Running { get; set; }

    [Column("PHASE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Phase { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("SCHED_RULE")]
    [StringLength(20)]
    [Unicode(false)]
    public string SchedRule { get; set; }

    [Column("WK_5_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string Wk5Collect { get; set; }

    [Column("DAY_COLLECT")]
    public int? DayCollect { get; set; }

    [Column("JAN_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string JanCollect { get; set; }

    [Column("FEB_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string FebCollect { get; set; }

    [Column("MAR_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string MarCollect { get; set; }

    [Column("APR_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string AprCollect { get; set; }

    [Column("MAY_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string MayCollect { get; set; }

    [Column("JUN_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string JunCollect { get; set; }

    [Column("JUL_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string JulCollect { get; set; }

    [Column("AUG_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string AugCollect { get; set; }

    [Column("SEP_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string SepCollect { get; set; }

    [Column("OCT_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string OctCollect { get; set; }

    [Column("NOV_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string NovCollect { get; set; }

    [Column("DEC_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string DecCollect { get; set; }

    [Column("DAYS_AHEAD")]
    public int? DaysAhead { get; set; }

    [Column("SAMPLE_TYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string SampleType { get; set; }

    [Column("EARLY_COLLECT_DAYS")]
    public int? EarlyCollectDays { get; set; }

    [Column("LATE_COLLECT_DAYS")]
    public int? LateCollectDays { get; set; }

    [Column("CUSTOMER_COLLECT")]
    [StringLength(1)]
    [Unicode(false)]
    public string CustomerCollect { get; set; }

    [Column("RETURN_DAYS")]
    public int? ReturnDays { get; set; }

    [Column("DROP_OFF_CONTAINERS")]
    [StringLength(1)]
    [Unicode(false)]
    public string DropOffContainers { get; set; }

    [Column("EARLY_DROP_OFF_DAYS")]
    public int? EarlyDropOffDays { get; set; }

    [Column("LATE_DROP_OFF_DAYS")]
    public int? LateDropOffDays { get; set; }

    [Column("DROP_OFF_LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string DropOffLocation { get; set; }

    [Column("PICKUP_CONTAINERS")]
    [StringLength(1)]
    [Unicode(false)]
    public string PickupContainers { get; set; }

    [Column("EARLY_PICKUP_DAYS")]
    public int? EarlyPickupDays { get; set; }

    [Column("LATE_PICKUP_DAYS")]
    public int? LatePickupDays { get; set; }

    [Column("PICKUP_LOCATION")]
    [StringLength(20)]
    [Unicode(false)]
    public string PickupLocation { get; set; }

    [Column("R4_BASE_DATE", TypeName = "datetime")]
    public DateTime? R4BaseDate { get; set; }

    [Column("R4_DAYS")]
    public int? R4Days { get; set; }

    [Column("C_SAMPLING_REASON")]
    [StringLength(20)]
    [Unicode(false)]
    public string CSamplingReason { get; set; }

    [Column("C_WEEK_SELECTION")]
    [StringLength(100)]
    [Unicode(false)]
    public string CWeekSelection { get; set; }
}