// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[Table("UNITS")]
public partial class Units
{
    [Key]
    [Column("UNIT_CODE")]
    [StringLength(20)]
    [Unicode(false)]
    public string UnitCode { get; set; }

    [Column("DISPLAY_STRING")]
    [StringLength(20)]
    [Unicode(false)]
    public string DisplayString { get; set; }

    [Column("CHANGED_BY")]
    [StringLength(20)]
    [Unicode(false)]
    public string ChangedBy { get; set; }

    [Column("CHANGED_ON", TypeName = "datetime")]
    public DateTime? ChangedOn { get; set; }

    [Column("REMOVED")]
    [StringLength(1)]
    [Unicode(false)]
    public string Removed { get; set; }

    [Column("EXT_LINK")]
    [StringLength(254)]
    [Unicode(false)]
    public string ExtLink { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string GroupName { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(254)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("CATEGORY")]
    [StringLength(20)]
    [Unicode(false)]
    public string Category { get; set; }

    [Column("BASE")]
    [StringLength(1)]
    [Unicode(false)]
    public string Base { get; set; }

    [Column("OFFSET")]
    public float? Offset { get; set; }

    [Column("FACTOR")]
    public float? Factor { get; set; }

    [Column("FORMULA_SUB")]
    [StringLength(50)]
    [Unicode(false)]
    public string FormulaSub { get; set; }
}