// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LabBI.Module.BusinessObjects.BusinessObjects;

[PrimaryKey("TableName", "Name")]
[Table("VERSIONS")]
[Index("Name", Name = "VERSIONS_NAME8197")]
[Index("TableName", Name = "VERSIONS_TABLE6472")]
public partial class Versions
{
    [Key]
    [Column("TABLE_NAME")]
    [StringLength(20)]
    [Unicode(false)]
    public string TableName { get; set; }

    [Key]
    [Column("NAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("VERSION")]
    public int? Version { get; set; }
}